name: turbopy
channels:
        - defaults
dependencies:
        - python>=3.11
        - numpy
        - scipy
        - xarray
        - matplotlib
        - pandas
        - pytest-runner
        - pytest
        - pytest-cov
        - sphinx
        - pip
        - pip:
          - qtoml
          - livereload
          - formic2
          - sphobjinv
          - sphinx_rtd_theme
